### PR TITLE
Pipeline for Gitlab

### PR DESCRIPTION
**Pull request by kanaruna**
Creating a pipeline that builds and tests on a Gitlab docker image (Ubuntu 18.04)

### CODE REVIEW

**Comment by knocte** [comment]
@kanaruna thanks for your effort on this but I never stated in #4 that I wanted any F# code at all. You did too much :) bash scripts are fine, as running the tests should be super simple.

**Comment by knocte** [comment]
Quoting myself in #4:

> it should compile and run tests (no need to configure...

**Comment by kanaruna** [comment]
Sorry I thought I made it clear that I was re-using the scripts (actually https://github.com/knocte/fsx made me curious). If it is an issue I could rewrite the pipeline in bash, and obviously it should be faster.

**Comment by knocte** [comment]
Yeah I really like fsx and F# but for this task and this repo in particular it's a bit overkill, please rewrite using the simplest thing possible that works.

**Pull request closed without merging**
